### PR TITLE
fixed error messages for methods and properties

### PR DESCRIPTION
**Pull request by fabpot**
alternative (#151) fix for #147

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by aik099** [comment]
Ha, I haven't noticed the funny part about this PR where line was moved up. I thought it was now line.

Then :+1: too.

**Comment by apheleia** [comment]
Yes, this is the proper fix for the issue :+1:

**Comment by mickaelandrieu** [comment]
:+1:

**Pull request merged**
