### PR TITLE
upgraded to Symfony 3.0

### LINKED ISSUE #232: Sami is not compatible with Laravel 5.3
I am using Larvel 5.3 and try to installing Sami 3.3 and gets a few composer error about dependency collisions. How can I solve it?

### PR DESCRIPTION
**Pull request by fabpot**
Upgrading to Symfony 3.0 means : 

* removal of 5.3 and 5.4 support;
* bumping to a new major version.

As we have a new major version, I have also:

* removed support for Twig 1.x;
* upgraded to PHPParser version 3.0.

Fixes #232, #192, #217, #216, and #228

### CODE REVIEW

**Comment by fabpot** [comment]
@davidsoderberg @gquemener @GrahamCampbell @schnittstabil @javiereguiluz @KKSzymanowski @sas1024 @krzysiekpiasecki Can you test this new version and tell me if it fixes your issues before I merge it and release a new major version?

**Comment by KKSzymanowski** [comment]
Sorry, but my package no longer uses Sami, so I can't really test it.

**Comment by davidsoderberg** [comment]
Sorry I do not use sami any more.

**Comment by krzysiekpiasecki** [comment]
#228 is fixed by Sami 4.0.0-DEV

**Comment by schnittstabil** [comment]
LGTM :+1:

**Pull request merged**
