### PR TITLE
Closes #84 - fix php documentation links

### LINKED ISSUE #84: Links to php documentation doesn't work
In case when a class implements one of built-in interfaces (e.g. ArrayAccess), then a link to PHP website is built. However link isn't clickable:

1. go to http://www.qa-tools.io/api/master/
2. type `abstractelementcoll` in search box on the left
3. click on first search result
4. click on `ArrayAccess` on the right

When I open page on the right without a frameset, then link works. I guess there is some kind of JS that handles internal link processing and doesn't make an exception for absolute links to other domains.

sami_externallinksnotclickable

### PR DESCRIPTION
**Pull request by mickaelandrieu**
@fabpot should we add locale support for this stuff ? I think it's out of scope for now.

### CODE REVIEW

**Comment by aik099** [comment]
Wasn't existing implementation working. I thought php.net has some clever redirect from these urls.

**Comment by mickaelandrieu** [comment]
@aik099 like ?

**Comment by aik099** [comment]
Like this http://www.php.net/SplFileInfo . No need to explicitly specify anything, because locale comes from cookies and needed page is shown automatically.

**Comment by mickaelandrieu** [comment]
This has no "known" extension, so I suppose this is why you can't be redirect to it.

We have 2 strategies here:

* Add a ``target="_blank" into the link, to enforce open a new tab.
* Use my patch (I don't see why this is not "clever")

The both ways your bug is fixed.

**Comment by aik099** [comment]
Ah that target=_blank. I've also reported this somewhere that links to PHP documentation just doesn't work because there catchall click handler to redirect inside the generated documentation.

> Use my patch (I don't see why this is not "clever")

I haven't said, that it's not clever. I just said that class documentation is shown anyway with currently implement link building. Problem was in missing target attribute.

**Comment by fabpot** [comment]
Thank you @mickaelandrieu.

**Pull request merged**
