### PR TITLE
Updated to Symfony 3

### PR DESCRIPTION
**Pull request by gquemener**
I'm not sure this PR should be merged on master.
Don't hesitate to tell me on which one you'd like me to recreate it if it's not the correct one.

### CODE REVIEW

**Comment by gquemener** [comment]
Something's wrong with the "blackfire" build:

``` bash
1.49s$ if [[ "$BLACKFIRE" = "on" ]]; then

      openssl aes-256-cbc -K $encrypted_16ab3ffdcd52_key -iv $encrypted_16ab3ffdcd52_iv -in .blackfire.travis.ini.enc -out ~/.blackfire.ini -d

      curl -L https://blackfire.io/api/v1/releases/agent/linux/amd64 | tar zxpf -

      chmod 755 agent && ./agent --config=~/.blackfire.ini --socket=unix:///tmp/blackfire.sock &

  fi

  

iv undefined

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100   620    0   620    0     0   1664      0 --:--:-- --:--:-- --:--:--  2190

100 2907k  100 2907k    0     0  1984k      0  0:00:01  0:00:01 --:--:-- 2939k
install

[2015-11-30T23:22:34Z] ERROR: Error while reading configuration file: No [blackfire] section found
```

**Comment by gquemener** [comment]
ping @fabpot

**Comment by fabpot** [comment]
Using Symfony 3 means upgrading to PHP 5.5, not sure it is worth it.

**Comment by aik099** [comment]
Maybe we can do combined constraint as in other projects, like `^2.5|^3.0`.

**Comment by GrahamCampbell** [comment]
> Maybe we can do combined constraint as in other projects, like ^2.5|^3.0.

Not possible because we ship a lock file.

**Comment by aik099** [comment]
For Symfony 3-based projects, where Sami is used as a dependency, not as PHAR that would make life easier.

**Comment by GrahamCampbell** [comment]
True.

**Comment by schnittstabil** [comment]
Is there any progress on this? I'm a bit lost, I want to use `sami` and `symfony/finder ^3.0` as dependencies, but `sami` depends on `symfony/finder ~2.1` :unamused:

**Comment by javiereguiluz** [comment]
Same error here. I can't upgrade an application to Symfony 3.0 because of the sami dependency.

**Comment by gquemener** [comment]
Sorry here, I ain't got no time to rebase nor review this PR. I'm keeping it open for review by an admin.

Feel free to close :)

Cheers!

**Comment by mzur** [comment]
I support this update since Laravel 5.3 is no longer compatible with Sami. The official Laravel API documentation requires a hack to still use Sami. PHP 5.4 is no longer supported for over a year now so maybe the update can be reconsidered?

**Comment by fabpot** [comment]
Closing in favor of #235

**Pull request closed without merging**
