### PR TITLE
travis: PHP 7.0 nightly added

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by aik099** [comment]
Somebody is mass sending PR for adding PHP 7.0 to `.travis.yml` I see :wink:

**Comment by TomasVotruba** [comment]
;) "Be the change you want to see"

**Comment by fabpot** [comment]
Thank you @TomasVotruba.

**Comment by TomasVotruba** [comment]
Thanks @fabpot

**Pull request merged**
