### PR TITLE
.gitignore - add composer.lock file

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by stof** [comment]
Given that Sami is distributed as a phar, this change looks wrong to me.

**Comment by aik099** [comment]
Which particular change to `.gitignore` is troubling you?

**Comment by stof** [comment]
the one described in the title of the PR: the composer.lock file.

**Comment by keradus** [comment]
Addning `composer.lock`.
For me this file should be either in repo, either in .gitignore.

Before that commit it wasn't anywhere, therefore git offer adding it when contributing each time over and over

**Comment by stof** [comment]
Well, it should be in the repo IMO when the project is distributed as phar

**Comment by fabpot** [comment]
I agree with @stof, that was overlooked back then. We should distribute the .lock in the repo.

**Comment by GrahamCampbell** [comment]
Same goes for php-cs-fixer really then.

**Comment by stof** [comment]
@GrahamCampbell indeed

**Comment by keradus** [comment]
I agree it is cool for having .lock for application, and not for libs.
Just one thing - someone should maintain it and update deps.

Please see #148

**Comment by GrahamCampbell** [comment]
> I agree it is cool for having .lock for application, and not for libs.

If we've got a phar, it effectively means we are an application. :)

**Comment by keradus** [comment]
> > I agree it is cool for having .lock for application, and not for libs.
> 
> If we've got a phar, it effectively means we are an application. :)

Therefore I agreed with way of dealing with .lock file ;)

**Pull request merged**
