### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by NightFox7**
Replate sami.php with sami.phar

### CODE REVIEW

**Comment by aik099** [comment]
We have `sami.php` file too.

**Comment by NightFox7** [comment]
I only included the sami.phar file to my project as it was described in the installation part. So when I use
```
$ php sami.php
````
I get the following error message: Could not open input file: sami.php

**Comment by aik099** [comment]
I guess, when Sami installed globally via Composer or as vendor in a project, then sami.php works.

**Comment by NightFox7** [comment]
Yes I think so as well. But to follow the installation foot steps I suggest that you change the command to php sami.phar instead.

**Comment by aik099** [comment]
Maybe we should document both ways of running.

**Comment by GrahamCampbell** [comment]
:-1: for this as is.

**Comment by fabpot** [comment]
I think this change makes sense as the README starts by recommending the user to download the phar archive. So, the first of the README uses `sami.phar` and then we are using `sami.php`. So, this PR is really a bug fix for this inconsistency.

**Comment by fabpot** [comment]
Thank you @NightFox7.

**Pull request merged**
