### PR TITLE
Add TODO (original #298)

### PR DESCRIPTION
**Pull request by serieznyi**
Move changes from PR #298  and resolve conflict

### CODE REVIEW

**Comment by serieznyi** [comment]
@fabpot I think what TODO list more comfortable in phpDocumentator (especial parsing TODO from simple comments), but I can`t do it in this moment. Maybe I try it later.

**Comment by fabpot** [comment]
Thinking about this one a bit more, I don't think it is that useful. API docs are for end users, not for core contributors. End users want to get information about what is available today. TODOs are likely be done in a real issue tracker. Maybe TODOs are something of the past that we don't want to promote in Sami.

**Comment by serieznyi** [comment]
@fabpot Maybe you right. I use Sami for generating inner documentation for developers so I need all information about TODOs and other thinks . 
I think I can use some other tool for TODOs.

What you think about page with information of deprecated functionality? 
I can little change this code and we get it.

**Comment by fabpot** [comment]
Ok, let's close it then.

**Pull request closed without merging**
