### PR TITLE
build cache broke source link between versions

### PR DESCRIPTION
**Pull request by gza**
When using remote_repository conf to provide links to gitlab or github source, a class that didn't change from previous version has the same link (that point to previous version).

So, cache should be disabled in this case.

### CODE REVIEW

**Comment by aik099** [comment]
This is the only of many cases. In general if in used theme you have content that is changed between different versions/branches/tags while file (for which documentation is generated) stays the same in each version you'll have this problem.

If only there could be an automated way to disable caching depending on twig template content.

Another problem, that might be related to caching is #219.

P.S.
I saw, that you've addressed version dropdown problem in #239 .

**Comment by gza** [comment]
It's difficult to predict if the result of a template without render or analyze it. This could have a higher cost than the cache benefit.

**Comment by aik099** [comment]
But with your change if GitHub links are being used you completely ignore caching. Instead I would rather adapt caching key to reflect that difference (e.g. include base url for a branch on GitHub in cache key). This way if you render the same version twice you can use cache anyway.

**Comment by aik099** [comment]
Ah, I've debugged your change and see now, that you don't copy cache from previous parsed version into new version of remote repository is configured. Looks good to me.

**Comment by gza** [comment]
Yes, when remote repository is configured each page is unique, even with the same code.
Perhaps, some JavaScript could help, like in #239 . But, browser's popup protections could make opening target in a new window/tab hard to implement.

**Pull request closed without merging**
