### PR TITLE
Defaulting to ./sami.cfg.php if not passed a config

### PR DESCRIPTION
**Pull request by kevinkhill**
Simple edit for defaulting to using the config file in the cwd if not given one.

### CODE REVIEW

**Comment by aik099** [comment]
There were no such thing as default config before, right? Maybe call it `sami_config.php.dst` instead.

**Comment by kevinkhill** [comment]
Ahhh, you're right, I'm not sure where I got the name from. I might have copied it from some blog/guide/forum, I don't remember now. It's a personal preference (maybe others too?) to being able to leave it off and have a default be used. Like Vagrantfile, gulpfile.js, phpunit.xml, etc....

**Comment by greg-1-anderson** [comment]
Following the phpunit model: default to `sami_config.php` if it exists, otherwise default to `sami_config.php.dist`

**Comment by fabpot** [comment]
Closing as the repo is not maintained anymore.

**Pull request closed without merging**
